# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Pode, é possivel trabalhar com objetos mais dinamicos concatenando diferentes tipos de informação.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [28]:
lista_de_nome_de_genes = ['BRCA1', 'TP53', 'EGFR', 'VEGFA', 'APOE']
lista_brca1 = [
  len(lista_de_nome_de_genes[0]), 
  lista_de_nome_de_genes[0][0:2], 
  lista_de_nome_de_genes[0].lower().count('a'),
  lista_de_nome_de_genes[0].lower().count('hu')
]

lista_tp53 = [
  len(lista_de_nome_de_genes[1]), 
  lista_de_nome_de_genes[1][0:2], 
  lista_de_nome_de_genes[1].lower().count('a'),
  lista_de_nome_de_genes[1].lower().count('hu')
]

lista_egfr = [
  len(lista_de_nome_de_genes[2]), 
  lista_de_nome_de_genes[2][0:2], 
  lista_de_nome_de_genes[2].lower().count('a'),
  lista_de_nome_de_genes[2].lower().count('hu')
]

lista_vegfa = [
  len(lista_de_nome_de_genes[3]), 
  lista_de_nome_de_genes[3][0:2], 
  lista_de_nome_de_genes[3].lower().count('a'),
  lista_de_nome_de_genes[3].lower().count('hu')
]

lista_apoe = [
  len(lista_de_nome_de_genes[4]), 
  lista_de_nome_de_genes[4][0:2], 
  lista_de_nome_de_genes[4].lower().count('a'),
  lista_de_nome_de_genes[4].lower().count('hu')
]

matriz_exercicio_2 = [lista_brca1, lista_tp53, lista_egfr, lista_vegfa, lista_apoe]
print(matriz_exercicio_2)

[[5, 'BR', 1, 0], [4, 'TP', 0, 0], [4, 'EG', 0, 0], [5, 'VE', 1, 0], [4, 'AP', 1, 0]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [29]:
import numpy as np
matriz_exercicio_2_numpy = np.array(matriz_exercicio_2)
print(matriz_exercicio_2_numpy)

[['5' 'BR' '1' '0']
 ['4' 'TP' '0' '0']
 ['4' 'EG' '0' '0']
 ['5' 'VE' '1' '0']
 ['4' 'AP' '1' '0']]

## 4 – Recupere todos os itens do terceiro gene.

In [30]:
matriz_exercicio_2_numpy[2]

array(['4', 'EG', '0', '0'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [24]:
matriz_exercicio_2_numpy[[1, 3], 1:3]

array([['TP', '0'],
       ['VE', '1']], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [34]:
import pandas as pd
dicionario_exercicio_10 = {
  lista_de_nome_de_genes[0]: lista_brca1,
  lista_de_nome_de_genes[1]: lista_tp53,
  lista_de_nome_de_genes[2]: lista_egfr,
  lista_de_nome_de_genes[3]: lista_vegfa,
  lista_de_nome_de_genes[4]: lista_apoe
}
dicionario_exercicio_10
result_frame = pd.DataFrame(dicionario_exercicio_10)
result_frame.index.name = 'gene_name'
result_frame.to_csv('../storage/aula_004.csv')
result_frame

          BRCA1 TP53 EGFR VEGFA APOE
gene_name
0             5    4    4     5    4
1            BR   TP   EG    VE   AP
2             1    0    0     1    1
3             0    0    0     0    0

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [15]:
result = result_frame.iloc[[0,2]]
result

  BRCA1 TP53 EGFR VEGFA APOE
0     5    4    4     5    4
2     1    0    0     1    1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [16]:
result = result_frame.iloc[3, [0, 2]]
result

BRCA1    False
EGFR     False
Name: 3, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [19]:
df_florida = pd.read_csv('../storage/data.csv')
df_florida
florida_dict = {
  "size": len(df_florida),
  "classes": [str(dtype) for dtype in df_florida.dtypes],
  "elemen_by_class": [df_florida.select_dtypes(include=[dtype]).shape[1] for dtype in df_florida.dtypes.unique()]
}
colunas = [0, 3, 8]

florida_dict["medias"] = [df_florida.iloc[:, i].mean() for i in colunas]
florida_dict["desvios"] = [df_florida.iloc[:, i].std() for i in colunas]
florida_dict["terceiro_quartil"] = [df_florida.iloc[:, i].quantile(0.75) for i in colunas]
florida_dict

{'size': 36634,
 'classes': ['int64',
  'str',
  'str',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'int64',
  'float64',
  'float64',
  'str',
  'str',
  'int64'],
 'elemen_by_class': [3, 4, 11],
 'medias': [np.float64(548661.9371894961),
  np.float64(731478.0068460993),
  np.float64(2571004.0973420865)],
 'desvios': [np.float64(259912.9264939009),
  np.float64(17523003.588415083),
  np.float64(20367766.569178067)],
 'terceiro_quartil': [np.float64(774252.0),
  np.float64(0.0),
  np.float64(1128871.1824999999)]}