# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Pode, é possivel trabalhar com objetos mais dinamicos concatenando diferentes tipos de informação.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [7]:
lista_de_nome_de_genes = ['BRCA1', 'TP53', 'EGFR', 'VEGFA', 'APOE']
lista_brca1 = [
  len(lista_de_nome_de_genes[0]), 
  lista_de_nome_de_genes[0][0:2], 
  lista_de_nome_de_genes[0].lower().count('a'),
  lista_de_nome_de_genes[0].lower().find('hu') > -1
]

lista_tp53 = [
  len(lista_de_nome_de_genes[1]), 
  lista_de_nome_de_genes[1][0:2], 
  lista_de_nome_de_genes[1].lower().count('a'),
  lista_de_nome_de_genes[1].lower().find('hu') > -1
]

lista_egfr = [
  len(lista_de_nome_de_genes[2]), 
  lista_de_nome_de_genes[2][0:2], 
  lista_de_nome_de_genes[2].lower().count('a'),
  lista_de_nome_de_genes[2].lower().find('hu') > -1
]

lista_vegfa = [
  len(lista_de_nome_de_genes[3]), 
  lista_de_nome_de_genes[3][0:2], 
  lista_de_nome_de_genes[3].lower().count('a'),
  lista_de_nome_de_genes[3].lower().find('hu') > -1
]

lista_apoe = [
  len(lista_de_nome_de_genes[4]), 
  lista_de_nome_de_genes[4][0:2], 
  lista_de_nome_de_genes[4].lower().count('a'),
  lista_de_nome_de_genes[4].lower().find('hu') > -1
]

matriz_exercicio_2 = [lista_brca1, lista_tp53, lista_egfr, lista_vegfa, lista_apoe]
print(matriz_exercicio_2)

[[5, 'BR', 1, False], [4, 'TP', 0, False], [4, 'EG', 0, False], [5, 'VE', 1, False], [4, 'AP', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [8]:
import numpy as np
matriz_exercicio_2_numpy = np.array(matriz_exercicio_2)
print(matriz_exercicio_2_numpy)

[['5' 'BR' '1' 'False']
 ['4' 'TP' '0' 'False']
 ['4' 'EG' '0' 'False']
 ['5' 'VE' '1' 'False']
 ['4' 'AP' '1' 'False']]

## 4 – Recupere todos os itens do terceiro gene.

In [5]:
matriz_exercicio_2_numpy[2]

array(['4', 'EG', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [9]:
matriz_exercicio_2_numpy[[1, 3], [2]]

array(['0', '1'], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [10]:
import pandas as pd
dicionario_exercicio_10 = {
  lista_de_nome_de_genes[0]: lista_brca1,
  lista_de_nome_de_genes[1]: lista_tp53,
  lista_de_nome_de_genes[2]: lista_egfr,
  lista_de_nome_de_genes[3]: lista_vegfa,
  lista_de_nome_de_genes[4]: lista_apoe
}
dicionario_exercicio_10
result_frame = pd.DataFrame(dicionario_exercicio_10)
result_frame

   BRCA1   TP53   EGFR  VEGFA   APOE
0      5      4      4      5      4
1     BR     TP     EG     VE     AP
2      1      0      0      1      1
3  False  False  False  False  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [12]:
result = result_frame.iloc[[0,2]]
result

  BRCA1 TP53 EGFR VEGFA APOE
0     5    4    4     5    4
2     1    0    0     1    1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [13]:
result = result_frame.iloc[3, [0, 2]]
result

BRCA1    False
EGFR     False
Name: 3, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.