# Exercício:

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

## 01 – Usando o método np.random.normal(), gere valores de expressão gênica de um conjunto de 1.000 genes. Esse conjunto de ter valores up e downregulated.

In [ ]:
import numpy as np
mu, sigma = 5, 2
gene_expr_array = np.random.normal(mu, sigma, size=1000)
gene_expr_array

array([ 7.18277271,  3.35664241,  2.46917647,  5.65727263,  3.36623626,
        6.63511677,  4.75651677,  3.7861793 ,  3.77316183,  1.66840615,
        7.95548305,  2.63868159,  3.27473999,  5.56592872,  6.80240493,
        9.5113742 ,  5.22233579,  3.77327188,  3.54523246,  4.25910577,
        4.72119361,  5.13352709,  5.26298543,  7.35906255,  7.6501384 ,
        4.62804094,  2.01194315,  2.89152099,  4.6108606 ,  6.14152532,
        6.39290211,  7.91476794,  2.39028092,  5.83319253,  3.68626705,
        6.55248761,  3.88380677,  4.94463356,  7.7609696 ,  2.70485279,
        4.88202895,  6.36792563,  7.29471253,  3.79487183,  6.73849346,
        1.62657245,  4.53986138,  5.69432773,  5.41207022,  0.37712347,
        3.95819562,  3.38596942,  7.94851812,  4.40647446,  7.30606965,
        6.7585349 ,  0.81681986,  5.85748915,  5.54832282,  7.29446809,
        4.35529187,  4.28142519,  3.86468475,  2.29915024,  8.09862417,
        7.61260609,  2.58304532,  0.91711842,  5.89631913,  3.71031629,
        5.75820553,  6.12321379,  1.700057  ,  5.05778616,  4.72935444,
        2.7846015 ,  7.01294738,  2.63074116,  6.17075991,  7.0960211 ,
        5.66969944,  3.51825367,  3.29935414,  5.0492543 ,  7.86603187,
        5.04286881,  4.54084971,  5.53491036,  7.42280949,  2.93231163,
        3.76775904,  5.89663268,  4.07556121,  3.7246623 ,  3.26493286,
        2.53314288,  7.24591456,  6.35348648,  5.77699796,  3.45982446,
        4.08006382,  6.15626102,  2.86212883,  9.39195798,  4.81249816,
        7.70962356,  3.99685246,  7.69960397,  6.47848768,  6.57633663,
        3.11201544,  3.24023522,  3.41513947,  5.96446183,  5.01475581,
        5.31030297,  2.85324128,  2.86414275,  3.1119433 ,  2.22412532,
        7.49738867,  6.51231924,  4.85784872,  7.34206263,  2.8217938 ,
        3.39566655,  4.81460744,  6.03041633,  6.30350168,  2.70591873,
       -0.6735133 ,  1.38353876,  3.90890105,  3.41976333,  4.96770237,
        4.9557579 ,  6.20062343,  3.7654197 ,  4.44523492,  2.54800079,
        5.06053773,  8.52215782,  5.57006969,  4.53232506,  3.90241612,
        7.32850227,  5.06195193,  7.21594899,  7.76114725,  3.80714025,
        4.91070565,  7.65979137,  7.85900777,  4.16241262,  5.37458707,
        6.97080548,  6.91767411,  5.51337083,  6.45071811,  2.40574919,
        6.32518813,  4.58839731,  4.10702585,  5.58560806,  2.18306834,
        5.52053053,  4.82378741,  2.04627287,  9.67877257,  7.07968157,
        6.58770004,  5.68194945,  2.02481665,  6.58653   ,  1.72427874,
        5.43475587,  7.37345638,  3.54100029,  4.49113283,  0.36483876,
        3.75084441,  4.55680424,  4.49048851,  4.01322985,  2.82543885,
        3.57438798,  5.23600094,  5.11686803,  9.02860266,  5.10372496,
        2.09184473,  9.52583743,  3.76898014,  7.25741423,  4.46758085,
        8.73973947,  3.87769499,  9.06505836,  1.26176656, 11.31893037,
        3.83789465,  6.00796033,  5.97615588,  5.59731982,  4.00094823,
        8.94765403,  3.86678218,  7.08170049,  5.42372093,  5.74159314,
        5.73629801,  6.96986763,  7.91606659,  5.55702674,  5.60753371,
        6.29040968,  8.24223564,  6.80063582,  5.39987197,  2.51367975,
        6.17328278,  3.75534881,  5.45696779,  5.79720212,  3.0706823 ,
        4.31074778,  4.59819529,  6.42274263,  9.1739716 ,  3.86547784,
        1.90953097,  3.47610389,  3.20407931,  7.86200897,  3.52235547,
        1.48590714,  4.4369049 ,  7.46594467,  3.38751683,  4.07720995,
        5.63153996,  3.23077119,  6.68366964,  7.32345071,  4.45599322,
        5.44264522,  7.82033042,  7.76046544,  8.02372244,  6.53245796,
        5.51589138,  3.50835633,  8.07177574,  8.71161217,  3.08061061,
        4.02708688,  2.30752827,  9.4844737 ,  7.23948583,  9.67644909,
        3.57925143,  8.30165983,  3.5601015 ,  2.38288213,  7.11579504,
        1.61335593,  2.90992833,  6.28734395,  6.77488901,  5.57960636,
        4.0151377 ,  3.76192775,  3.19259863,  3.86755144,  5.97704861,
        6.2887923 ,  7.10851543,  9.09313562,  3.88773056,  6.57233132,
        6.98669979,  6.06528671,  6.3299985 ,  5.37397538,  5.46892813,
        2.73131363,  1.69833818,  7.85710832,  5.07332551,  7.19581489,
        8.70689467,  6.28962767,  5.34846676,  3.57310365,  3.936342  ,
        6.72706345,  3.77147244,  4.39109731,  5.82380616,  2.59617048,
        4.69569618,  4.79294636,  3.90563072,  7.63068673,  5.84671315,
        6.15399474,  7.30216182,  3.64046647,  4.3319418 ,  1.02293125,
        6.88965383,  3.97269967,  3.8150758 ,  4.51197961,  4.44503504,
        4.54120848,  5.23788341,  2.34087825,  2.5169515 ,  3.49825952,
        8.22117011,  4.90076772,  7.74363218,  4.10428943, -1.12638454,
        4.36470221,  5.9726338 ,  3.44705977,  4.61638727,  2.51421181,
        5.23786944,  5.2256065 ,  5.17234929,  3.28231966,  2.97138793,
        7.86137495,  6.03497034,  5.54567272,  7.1475955 ,  5.14458423,
        2.67537892,  3.52102838,  6.63733799,  5.00207791,  8.18708483,
        5.50554658,  3.78707919,  3.78959943,  6.36570685,  5.50202007,
        5.34114194,  3.97008559,  2.95066097,  7.24937549,  7.80986947,
        5.80057087,  5.24373153,  7.05107587,  7.1105503 ,  4.00979295,
        7.71179644,  1.82605145,  4.07909904,  5.96155817,  6.77418153,
        4.98911072,  9.6243668 ,  2.08383053,  7.05882015,  4.82538195,
        6.14694134,  6.34319815,  0.76499063,  4.69235386,  5.39279992,
        4.19269976,  3.96317666,  4.3769352 ,  3.41192538,  1.18054885,
       10.36042157,  5.68708736,  3.67084567,  0.59543147,  6.27441464,
        6.87171519,  2.70210188,  3.09587919,  2.97764537,  4.52420734,
        3.50929004,  5.1566945 ,  4.03458715,  6.19052948,  6.71853895,
        7.03401679,  7.45470129,  5.04461968,  6.3326962 ,  4.62946898,
        4.15547579,  2.05282339,  0.73931007,  6.36791912,  5.58316117,
        2.37319464,  7.7708465 ,  6.2242441 ,  8.71189264,  2.49212159,
        0.64491792,  2.56492405,  6.50758691,  6.27308251,  8.87237154,
        5.76921981,  5.68330532,  8.39209023,  4.10672683,  8.70113326,
        6.9001531 ,  2.5163954 ,  4.46878079,  5.95063791,  5.17255192,
        1.9015284 ,  5.73933203,  4.75787916,  5.29115995,  3.17471661,
        6.31344536,  7.59943532,  7.43421464,  8.82815814,  8.53753149,
        3.21929121,  7.57105796,  9.49781095,  5.7511046 ,  3.07433006,
        3.52015813,  4.57161427,  7.19920896,  5.02802138,  2.42160416,
        3.78902652,  4.5475927 ,  7.13828004,  5.93279084,  2.239069  ,
        8.09619486,  7.14489535,  5.66755834,  4.86691827,  8.42337603,
        5.62435182,  4.87625437,  5.92269144,  4.96189677,  7.34484299,
        4.63758909,  4.52193612,  4.67420082,  5.29107094,  2.4512944 ,
        5.88348424,  2.87932198,  4.58201101,  7.75009421,  1.37392755,
        5.36683012,  8.220371  ,  4.67518339,  3.40129544,  3.45610929,
        4.67362276,  6.38433753,  5.59571078,  6.06707576,  4.67416121,
        1.82041066,  3.21529989,  5.68909875,  7.35284562,  2.26021784,
        5.03589543,  6.32527778,  5.52682452,  5.95258424,  4.39445344,
        6.22519345,  4.8363715 ,  3.48677865,  8.34759202,  7.76992437,
        1.93856007,  3.78857557,  3.8472601 ,  3.4073679 ,  5.3218293 ,
        3.53158224,  8.93915114,  2.65196125,  3.63951934,  5.87638588,
        6.07277379,  4.4209954 ,  3.71600335,  8.61455841,  5.93540555,
        5.65908672,  6.00700215,  6.2306853 ,  2.4698809 ,  4.01559163,
        8.40119663,  6.75161829,  3.89203257,  8.61136936,  6.22991063,
        6.40341565, -0.12845871,  4.68654617,  4.9437965 ,  0.73537992,
        7.9567097 ,  8.34233205,  5.30886329,  3.48555108,  3.39045538,
        6.32087083,  4.71443398,  5.52910719,  5.5954819 ,  5.72352974,
        9.22666371,  4.64567068,  3.6361329 ,  5.90205513,  5.66252912,
        6.03287985,  7.30443295,  5.83014465,  4.29073525,  3.35867247,
        3.0318252 ,  3.91449177,  2.10031951,  2.4115773 ,  5.30208116,
        5.6745343 ,  4.87158536,  7.1187503 ,  4.9214453 ,  0.17413304,
        4.1179384 ,  6.96278084,  2.57030656,  3.97637379,  3.52834681,
        4.09756533,  4.38622394,  4.73537158,  6.59369302,  6.82806572,
        5.40559024,  7.65928668,  3.64032436,  3.0025674 ,  4.94302313,
        5.7089515 ,  5.46994509,  7.41953289,  2.44397096,  2.68862176,
        3.07861749,  5.53097014,  5.90194951,  8.42400227,  7.25951399,
        0.44114037,  6.27918357,  6.94736458,  6.40490886,  5.03847177,
        3.46071629,  4.35561661,  7.74331718,  4.84648814,  8.16836146,
        8.00831873,  6.12077503,  4.35959127,  3.67105081,  5.78416056,
        3.68045455,  7.47453   ,  2.92442574,  4.78412618,  4.96659072,
        4.18910133,  4.30950815,  7.55336249,  2.25475806,  5.97933079,
        7.47922287,  6.41119971,  6.75554018,  6.99427307,  6.43363757,
        4.72167175,  1.58256747,  5.06736955,  2.68750259,  7.03277226,
        0.15891595,  5.67373142,  7.86542527,  6.59676476,  4.30324228,
        4.96952398,  8.28209116,  2.4778328 ,  1.12549292, 10.59031886,
        2.65186443,  3.72576089,  4.82149326,  6.35218166,  3.53873555,
        4.04479495,  4.26598955,  6.80792898,  3.80356856,  2.43384496,
        4.14875117,  4.51193206,  5.85736442,  3.24505757,  2.80412213,
        3.1274221 ,  2.61022442,  2.27974047,  6.35095543,  3.28424806,
        7.30139238,  5.20147451,  8.68613232,  9.05616369,  2.79050414,
        1.76331159,  1.79340579,  7.69805715,  7.48846428,  7.70980465,
        4.46570796,  3.98979231,  0.83459528,  4.39556846,  2.62301481,
        3.79352362,  2.93963343,  3.32561082,  1.81136378,  5.62821995,
        7.81668226,  7.14229615,  3.66553792,  0.6000649 ,  3.85698191,
        5.98240386,  5.99749174,  6.4851276 ,  5.22651882,  2.44363673,
        4.98272966,  4.78581072,  4.64071902,  7.10021636,  5.24331553,
        6.83910267,  4.58475017,  7.15784263,  2.97740072,  2.29611253,
        2.10482558,  2.72413595,  7.62139317,  2.61303926,  5.92454468,
        5.20534748,  6.48930824,  2.06201761,  5.89964554,  5.36510751,
        4.6613665 ,  4.74313836,  4.39729408,  3.88668589,  2.29806856,
        5.34890587,  4.60017095,  1.65681764,  2.57023127,  7.0159345 ,
        1.86518769,  2.50386746,  6.76874082,  3.88336624,  4.60951617,
        4.35131544,  3.41111628,  7.68317875,  6.98958073,  3.69924907,
        5.2914858 ,  4.93095542,  4.14276431,  5.88349687,  5.73464965,
        6.60734314,  0.47286393,  2.28441777,  3.44906088,  5.16734183,
        3.40810367,  6.34897561,  1.49064961,  2.46342503,  6.20655407,
        3.42899948,  2.27602319,  2.58039459,  5.12491985,  3.56911856,
        6.96890211,  4.83441457,  7.99788831,  5.6293243 ,  2.90636492,
        5.16568763,  7.90229103,  4.93893379,  6.8532483 ,  3.86541542,
        2.94550077,  3.80179862,  6.68884346,  5.70163846,  4.08046295,
        2.61017142,  8.33581796,  4.10611692,  4.79789813,  4.93828738,
        3.54948261,  6.15879138,  9.95510074,  6.32816555,  4.1883854 ,
        5.8445381 , 11.54548214,  3.01885237,  7.26958563,  5.89640324,
        4.33162757,  6.37214666,  6.43345512,  4.37947177,  6.646336  ,
        4.14595524,  7.02833799,  8.52666137,  6.64069896,  4.89585285,
        4.04968775,  3.87679031,  4.8579085 ,  6.48535815,  6.5695975 ,
        4.05751673,  3.98057797,  6.36712014,  6.46307056,  3.20340325,
        4.23249859,  4.71247596,  4.01439078,  4.99426604,  5.05701158,
        3.29186474,  6.48360975,  4.95042423,  9.75707663,  1.74755536,
        7.09888188,  6.96433409,  3.48369797,  4.42960276,  0.81717248,
        7.13008377,  6.45375161,  5.67882768,  7.49891008,  3.19299992,
       -0.53931886,  5.6906893 ,  6.44425418,  5.52214975,  3.20583679,
        4.118581  ,  7.33267153,  4.20190666,  7.49666271,  5.90436562,
        5.73652419,  6.49492842,  4.52120214,  0.08666718,  6.95409842,
        6.21957345,  6.31977601,  6.52245001,  3.70989968,  0.24447658,
        5.29787283,  4.59367666,  6.62925599,  3.06824699,  6.9159662 ,
        2.58856646,  5.20079487,  4.73160125,  7.1564843 ,  6.82720159,
        6.01321877,  2.84318662,  6.05020123,  3.3925964 ,  6.43376758,
        5.74352332,  4.30981223,  5.37766614,  5.50107244,  6.48779533,
        1.61961689,  2.72258119,  5.10426455,  4.26796342,  3.78090878,
        8.9756097 ,  7.0963399 ,  4.91539538,  3.72764139,  6.47101777,
        3.75748181,  5.6907835 ,  4.33775511,  5.41494414,  4.46340523,
        6.61810249,  7.33135236,  7.29402072,  5.45404443,  4.85345805,
        5.87398894,  3.37187924,  4.80021058,  4.55981366,  2.75070889,
        6.29985984,  4.92834661,  5.6293934 ,  5.62449554,  6.02779999,
        6.95840192,  1.89170471,  4.40660987,  5.645362  ,  8.33608208,
        4.97528401,  3.13684413,  5.4402626 ,  5.98636604,  7.18183907,
        4.49568554,  6.29122889,  7.53827205,  2.67473667,  3.36582505,
        6.50867104,  4.05408579,  5.89114465,  2.46054265,  7.89770458,
        2.5928484 ,  6.10266855,  2.6838152 ,  5.83142587,  4.09583906,
        2.31484612,  8.15771531,  3.3971334 ,  5.44131788,  4.41122969,
        7.00471127,  5.16324323,  6.62279845,  4.6323414 ,  3.00687733,
        6.24489527,  8.07227247,  4.80684914,  6.34980867,  8.64328461,
        3.21676587,  9.64562517,  4.724983  ,  5.58714952,  2.07799729,
        5.96226074,  3.70900862,  9.26231866,  4.35168739,  1.86894607,
        2.84268502,  7.46578879,  3.74023231,  4.22935192,  2.64108003,
        3.65939846,  8.72514604,  6.78203629,  5.70332514,  4.26162485,
        4.18635692,  1.60013558,  6.35844128,  5.44661395,  4.14975934,
        5.56825984,  6.03460697,  5.96913418,  5.18708689,  3.85083706,
        4.58398615,  6.03664887,  5.43297971,  7.55693548,  4.18250546,
        5.35130145,  5.84915524,  5.91144307,  7.36410507,  1.01979442,
        3.98638362,  7.44999089,  5.74402955,  5.83853368,  5.75826467,
        8.45013975,  3.56472163,  6.96315557, -0.10456058,  4.32582906,
        4.35318433,  3.96688246,  5.66307373,  6.94956472,  5.43493263,
       -0.28975673,  7.75571935,  4.1803945 ,  5.29573234,  2.60964478,
        5.69506675,  4.40071547,  1.50153897,  6.90343304,  2.30078278,
        4.87200749,  6.27786598,  3.92754091,  1.37983496,  6.46115186,
        3.0472074 ,  6.42697858,  5.43166115,  2.92009929,  4.80378462,
        3.00023105,  7.23432402,  2.66167695,  7.65393349,  5.39181339,
        5.97600273, 11.90723015,  6.25121229,  3.6181812 ,  5.17507735])

## 02 – Usando o método np.random.randint(), gere valores para o número de genes diferencialmente expressos em um conjunto de 1.000 pacientes. Esse conjunto deve ter valores up e downregulated.

Instancie um objeto da classe DataFrame, com os dados gerados nos dois exercícios.

In [ ]:
gene_dif_expr = np.random.randint(low=0, high=100, size=1000)

import pandas as pd

df = pd.DataFrame({"expr":gene_expr_array, "dif":gene_dif_expr})
df

          expr  dif
0     7.182773   44
1     3.356642   77
2     2.469176   62
3     5.657273   49
4     3.366236   19
..         ...  ...
995   5.976003   42
996  11.907230   15
997   6.251212   66
998   3.618181   91
999   5.175077   94

[1000 rows x 2 columns]

## 03 – Categorize em grupos de 6 os dados contidos na DataFrame anterior, segundo critérios escolhidos por você. Explique os critérios.

R.: Pensei nos seguintes, para up  e down regulados, avaliar genes que tem baixa expressão, uma expressão mediana e expressão alta. Entender a dinamica da expressão genica em genes semelhantes pode ajudar a entender se existe alguma função diferente nesses genes em situações especificas, enquanto que entender a mudança de genes diferencialmente expressos podem auxiliar a explicar os diferentes desfechos dentro da linha experimental.

In [ ]:
df["reg"] = np.where(df["expr"] > df["expr"].mean(), 1, 0)
df
def categorizar_diferecialmente(value):
  if value < 33:
    return 'Pouco'
  elif value < 66:
    return 'Médio'
  else:
    return 'Muito'
df['dif_expr'] = df['dif'].apply(categorizar_diferecialmente)
df

          expr  dif  reg dif_expr
0     7.182773   44    1    Médio
1     3.356642   77    0    Muito
2     2.469176   62    0    Médio
3     5.657273   49    1    Médio
4     3.366236   19    0    Pouco
..         ...  ...  ...      ...
995   5.976003   42    1    Médio
996  11.907230   15    1    Pouco
997   6.251212   66    1    Muito
998   3.618181   91    0    Muito
999   5.175077   94    1    Muito

[1000 rows x 4 columns]

## 04 – Defina uma função em Python que receba uma pd.Series contendo uma variável quantitativa e retorne uma DataFrame contendo a tabela de frequência.

Obtenha a tabela de frequência das variáveis criadas nos exercícios 1 e 2.

In [ ]:
def return_freq_table(df: pd.DataFrame, column: str):
    freq_abs = df[column].value_counts().sort_index()
    freq_rel = df[column].value_counts(normalize=True).sort_index()
    freq = pd.DataFrame({
        "abso_simp": freq_abs,
        "relat_simp": freq_rel
    })
    return freq

In [ ]:
freq_ordinal = return_freq_table(df, "reg")
print(freq_ordinal)

freq_nominal = return_freq_table(df, "dif_expr")
print(freq_nominal)

     count  relat_simp
reg
0      501       0.501
1      499       0.499
          count  relat_simp
dif_expr
Muito       329       0.329
Médio       348       0.348
Pouco       323       0.323

## 05 – Gere os gráficos de barras e linhas para as frequências em cada umas das variáveis.

In [ ]:
plt.figure(figsize=(6,4))
sns.barplot(x=freq_ordinal.index, y=freq_ordinal["abso_simp"], color="skyblue")
plt.title("Frequência absoluta - Regulação")
plt.ylabel("Frequência")
plt.xlabel("Categorias")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(freq_ordinal.index, freq_ordinal["abso_simp"], marker="o", linestyle="-", color="blue")
plt.title("Frequência absoluta - Regulação (linha)")
plt.ylabel("Frequência")
plt.xlabel("Categorias")
plt.show()

KeyError: 'abso_simp'

### Expressão

In [ ]:

labels = ["Pouco", "Médio", "Muito"]
sns.countplot(x='dif_expr '+ 'cat', data=df)
plt.title("Contagem de categorias de expressão genica diferencial")
plt.show()

ValueError: Could not interpret value `dif_expr cat` for `x`. An entry with this name does not appear in `data`.

### Número

## 06 – Gere os histogramas para as variáveis obtidas nos exercícios 1 e 2.

## 07 – Gere um gráfico de dispersão para as variáveis obtidas nos exercícios 1 e 2.

## 08 – Gere o mesmo gráfico do exercício 06, porém, categorizado.

## 09 – Gere o mesmo gráfico do exercício 07, porém, categorizado.

## 10 – Indique o tipo da variável:

- Discreta
- Contínua
- Ordinal
- Nominal

| Variável | Valor |
| :--- | :---: |
| # de células positivas||
| % de células positivas||
| Faixa de pH||
| Valor de pH||
| mol/L||
| UFC||
| D.O.||
| Grupo Sanguíneo||
| Sorologia||